before_script:
  - export VERSION="${CI_PROJECT_NAMESPACE}_${CI_BUILD_ID}_$(date "+%Y-%m-%d-%H:%M:%S")"
  - export PROJECTROOT=`pwd`
  - export DOCKERPROJECTROOT='/srv/example/'

stages:
  - test
  - analysis

unittests:
  stage: test
  script:
    - phpunit --verbose -c phpunit.xml # Log files are configured in phpunit.xml
  artifacts: # Persist the files that we use as input for the analysis step 
    paths:
      - *.xml
    when: on_success

sonar:
  stage: analysis
  dependencies: # Include the log files produced during test stage 
    - unittests
  script:
    - docker run --rm --mount type=bind,source=$PROJECTROOT,target=$DOCKERPROJECTROOT --tmpfs $DOCKERPROJECTROOT/.scannerwork -w=$DOCKERPROJECTROOT nikhuber/sonar-scanner:3.0.3.778 sonar-scanner -Dsonar.projectVersion=$VERSION
