sudo: required

services:
  - docker

language: php

php:
  - 7.0

install:
  - rm -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini
  - composer validate
  - composer install

script:
#   # Static analyzer check
#   - if [ $TRAVIS_PHP_VERSION = '7.1' ]; then composer require "phpstan/phpstan:^0.9" && ./vendor/bin/phpstan analyze -c .phpstan.neon --level=4 --no-progress src;fi
#   # Check the code style
#   - if [ $TRAVIS_PHP_VERSION = '7.1' ]; then IFS=$'\n'; COMMIT_SCA_FILES=($(git diff --name-only --diff-filter=ACMRTUXB "${TRAVIS_COMMIT_RANGE}")); unset IFS; fi
#   - if [ $TRAVIS_PHP_VERSION = '7.1' ]; then composer require "friendsofphp/php-cs-fixer:^2.8" && ./vendor/bin/php-cs-fixer fix --config=.php_cs.php -v --dry-run --stop-on-violation --using-cache=no --path-mode=intersection -- "${COMMIT_SCA_FILES[@]}";fi
#   # Unit test
#   - ./vendor/bin/phpunit
#   # Integration test
#   - mkdir web && echo "Hello" > web/index.html
#   - bin/ppm start --workers=1 --bridge=StaticBridge --static-directory=web --max-requests=1 -v &
#   - sleep 5
#   - bin/ppm status
#   - curl -v -f "http://127.0.0.1:8080"
#   - bin/ppm status
#   - curl -v -f "http://127.0.0.1:8080"
#   - bin/ppm status
#   - bin/ppm stop
#   # Unit test
  - export DOCKERWORKDIR='/project-root'
#   - echo $DOCKERWORKDIR
#   - docker network create -d bridge sonar
#   - docker run -d --net=sonar --name sonarqube -p 9000:9000 -p 9092:9092 sonarqube
# - docker run --rm --network=sonar --mount type=bind,source="$(pwd)",target=$DOCKERWORKDIR -w=$DOCKERWORKDIR nikhuber/sonar-scanner:latest sonar-scanner
#   - docker ps
#   - sleep 60
#   - curl localhost:9000
#   - docker exec sonarqube ls
#   - docker exec sonarqube curl localhost:9000
#   - docker network ls
#   - s=`docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' sonarqube`
#   - echo $s
#   - curl $s:9000 -I
#   - docker run --rm --net=sonar tutum/curl curl -I sonarqube:9000
#   - docker run --rm --mount type=bind,source="$(pwd)",target=$DOCKERWORKDIR -w=$DOCKERWORKDIR nikhuber/sonar-scanner:latest sonar-scanner
  - docker run --rm --mount type=bind,source="$(pwd)",target=$DOCKERWORKDIR     -w=$DOCKERWORKDIR     nikhuber/sonar-scanner:latest sonar-scanner

matrix:
  fast_finish: true

# Cache package sources
cache:
  directories:
    - $HOME/.composer/cache
